# Generated by Django 6.0.3 on 2026-05-08 21:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_alter_country_phone_code'),
        ('services', '0009_drop_airport_models_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tour', serialize=False, to='services.service', verbose_name='الخدمة')),
                ('tour_type', models.CharField(choices=[('city_tour', 'جولة مدينة'), ('day_trip', 'رحلة نهارية'), ('inter_city', 'نقل بين المدن'), ('island_jetty', 'نقل إلى الجزر')], max_length=20, verbose_name='نوع الجولة')),
                ('duration', models.CharField(choices=[('half_day', 'نصف يوم'), ('full_day', 'يوم كامل'), ('one_way', 'اتجاه واحد')], max_length=20, verbose_name='المدة')),
                ('origin_text', models.CharField(blank=True, help_text='مثلاً: Bukit Bintang، Penang Airport', max_length=120, verbose_name='منطقة الانطلاق')),
                ('destination_text', models.CharField(help_text='مثلاً: Sunway Lagoon، Cameron Highlands، Jetty Pangkor', max_length=160, verbose_name='الوجهة')),
                ('price_pax_1_2', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر 1-2 شخص (MYR)')),
                ('price_pax_3_4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر 3-4 أشخاص (MYR)')),
                ('price_pax_5_6', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر 5-6 أشخاص (MYR)')),
                ('price_pax_7_8', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر 7-8 أشخاص (MYR)')),
                ('price_pax_10_12', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر 10-12 شخص (MYR)')),
                ('price_pax_14', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر 14 شخص (MYR)')),
                ('price_pax_40_bus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر 40 شخص — حافلة كاملة (MYR)')),
                ('margin_pct_1_2', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='نسبة الربح % لشريحة 1-2')),
                ('margin_pct_3_4', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='نسبة الربح % لشريحة 3-4')),
                ('margin_pct_5_6', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='نسبة الربح % لشريحة 5-6')),
                ('margin_pct_7_8', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='نسبة الربح % لشريحة 7-8')),
                ('margin_pct_10_12', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='نسبة الربح % لشريحة 10-12')),
                ('margin_pct_14', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='نسبة الربح % لشريحة 14')),
                ('margin_pct_40_bus', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='نسبة الربح % لحافلة 40')),
                ('tour_guide_fee_myr', models.DecimalField(blank=True, decimal_places=2, help_text='يُضاف فقط لو طُلب — عادة لجولات المدن', max_digits=12, null=True, verbose_name='رسم مرشد سياحي (MYR)')),
                ('currency', models.CharField(default='MYR', editable=False, max_length=3, verbose_name='العملة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours_arriving', to='locations.city', verbose_name='مدينة الوصول')),
                ('origin_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours_originating', to='locations.city', verbose_name='مدينة الانطلاق')),
            ],
            options={
                'verbose_name': 'جولة سياحية',
                'verbose_name_plural': 'الجولات السياحية والرحلات النهارية',
                'db_table': 'tour_excursion',
                'ordering': ['tour_type', 'destination_text'],
                'indexes': [models.Index(fields=['tour_type', 'duration'], name='tour_excurs_tour_ty_2e246e_idx'), models.Index(fields=['destination_text'], name='tour_excurs_destina_f8d3e7_idx')],
            },
        ),
    ]
