# Generated by Django 6.0.3 on 2026-05-08 22:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_excursions', '0002_seed_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_guide_margin_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='افتراضياً 15% — تُطبَّق على رسم المرشد عند تضمينه', max_digits=5, verbose_name='نسبة الربح على المرشد %'),
        ),
    ]
