# Generated by Django 6.0.3 on 2026-05-08 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_phone_code'),
        ('tours_excursions', '0003_tour_tour_guide_margin_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='locations.city', verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='locations.country', verbose_name='الدولة'),
        ),
    ]
