# Generated by Django 6.0.3 on 2026-05-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_excursions', '0004_tour_city_tour_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='الوصف بالعربية'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='الوصف بالإنجليزية'),
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/photos/%Y/%m/', verbose_name='الصورة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='تعليق')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours_excursions.tour', verbose_name='الجولة')),
            ],
            options={
                'db_table': 'tour_photo',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['tour', 'is_primary'], name='tour_photo_tour_id_fa132f_idx')],
            },
        ),
    ]
