# Generated by Django 6.0.3 on 2026-04-27 13:43

import apps.hero_hotels.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroHotelCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرّف فريد')),
                ('name', models.CharField(help_text='مثال: Mandarin Oriental', max_length=200, verbose_name='اسم الفندق')),
                ('logo', models.ImageField(help_text='صورة صغيرة (يُفضّل PNG شفاف)', upload_to=apps.hero_hotels.models.hero_hotel_logo_path, verbose_name='شعار الفندق')),
                ('stars', models.PositiveSmallIntegerField(default=5, help_text='من 1 إلى 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='عدد النجوم')),
                ('description', models.TextField(help_text='نص يظهر أسفل اسم الفندق في البطاقة', verbose_name='وصف الفندق')),
                ('location', models.CharField(help_text='مثال: Kuala Lumpur', max_length=100, verbose_name='الموقع')),
                ('card_image', models.ImageField(help_text='الصورة التي تظهر داخل بطاقة الفندق (يُفضّل 800×600 أو أعلى)', upload_to=apps.hero_hotels.models.hero_hotel_card_image_path, verbose_name='صورة البطاقة')),
                ('hero_image', models.ImageField(help_text='الصورة التي تظهر كخلفية للـ Hero بالكامل (يُفضّل 1920×1080 أو أعلى)', upload_to=apps.hero_hotels.models.hero_hotel_hero_image_path, verbose_name='صورة الخلفية')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='الرقم الأقل = يظهر أولاً في الدوران', verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='إذا أُلغي التفعيل، لن تظهر البطاقة في الصفحة الرئيسية', verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'بطاقة فندق Hero',
                'verbose_name_plural': 'بطاقات فنادق Hero',
                'db_table': 'hero_hotel_card',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
