# Generated by Django 6.0.3 on 2026-05-02 10:38

import apps.hero_hotels.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herohotelcard',
            name='card_type',
            field=models.CharField(choices=[('hotel', 'فندق'), ('partner', 'شريك'), ('sponsor', 'ممول/راعي'), ('custom', 'عام')], db_index=True, default='hotel', max_length=10, verbose_name='نوع البطاقة'),
        ),
        migrations.AddField(
            model_name='herohotelcard',
            name='card_video',
            field=models.FileField(blank=True, help_text='mp4/webm/mov — يفضّل أقل من 10MB، autoplay صامت', null=True, upload_to=apps.hero_hotels.models.hero_card_video_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v'])], verbose_name='فيديو البطاقة'),
        ),
        migrations.AddField(
            model_name='herohotelcard',
            name='cta_text',
            field=models.CharField(blank=True, help_text='مثال: "احجز الآن"، "تواصل معنا"', max_length=40, verbose_name='نص الزر'),
        ),
        migrations.AddField(
            model_name='herohotelcard',
            name='hero_video',
            field=models.FileField(blank=True, help_text='mp4/webm/mov — autoplay صامت', null=True, upload_to=apps.hero_hotels.models.hero_bg_video_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v'])], verbose_name='فيديو الخلفية'),
        ),
        migrations.AddField(
            model_name='herohotelcard',
            name='link_url',
            field=models.URLField(blank=True, help_text='https://...', verbose_name='رابط الزر'),
        ),
        migrations.AlterField(
            model_name='herohotelcard',
            name='card_image',
            field=models.ImageField(blank=True, help_text='يُفضّل 800×600 أو أعلى — استعمل هذه أو فيديو البطاقة', null=True, upload_to=apps.hero_hotels.models.hero_hotel_card_image_path, verbose_name='صورة البطاقة'),
        ),
        migrations.AlterField(
            model_name='herohotelcard',
            name='description',
            field=models.TextField(blank=True, help_text='نص يظهر أسفل الاسم في البطاقة', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='herohotelcard',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='يُفضّل 1920×1080 أو أعلى', null=True, upload_to=apps.hero_hotels.models.hero_hotel_hero_image_path, verbose_name='صورة الخلفية'),
        ),
        migrations.AlterField(
            model_name='herohotelcard',
            name='location',
            field=models.CharField(blank=True, help_text='للفنادق — مثال: Kuala Lumpur', max_length=100, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='herohotelcard',
            name='logo',
            field=models.ImageField(blank=True, help_text='صورة صغيرة (يُفضّل PNG شفاف)', null=True, upload_to=apps.hero_hotels.models.hero_hotel_logo_path, verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='herohotelcard',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, help_text='للفنادق فقط — من 1 إلى 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='عدد النجوم'),
        ),
    ]
