# Generated by Django 6.0.3 on 2026-03-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('rooms', '0002_roomtype_breakfast_included_roomtype_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموسم')),
                ('valid_from', models.DateField(verbose_name='سارية من')),
                ('valid_to', models.DateField(verbose_name='سارية إلى')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='hotels.hotel', verbose_name='الفندق')),
            ],
            options={
                'verbose_name': 'موسم',
                'verbose_name_plural': 'المواسم',
                'ordering': ['valid_from'],
            },
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لليلة')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الخصم (%)')),
                ('breakfast_included', models.BooleanField(default=False, verbose_name='يشمل الإفطار')),
                ('currency', models.CharField(default='MYR', max_length=3, verbose_name='العملة')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='rooms.roomtype', verbose_name='نوع الغرفة')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.season', verbose_name='الموسم')),
            ],
            options={
                'verbose_name': 'تسعير غرفة',
                'verbose_name_plural': 'أسعار الغرف',
                'unique_together': {('season', 'room_type')},
            },
        ),
    ]
