# Generated by Django 6.0.3 on 2026-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomprice',
            name='currency',
        ),
        migrations.AddField(
            model_name='roomprice',
            name='child_with_bed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر طفل بسرير'),
        ),
        migrations.AddField(
            model_name='roomprice',
            name='child_without_bed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر طفل بدون سرير'),
        ),
        migrations.AddField(
            model_name='roomprice',
            name='infant_with_bed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر رضيع بسرير'),
        ),
        migrations.AddField(
            model_name='roomprice',
            name='infant_without_bed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر رضيع بدون سرير'),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='breakfast_included',
            field=models.BooleanField(default=False, verbose_name='يشمل فطور الصباح'),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الغرفة لليلة'),
        ),
    ]
