# Generated by Django 6.0.3 on 2026-05-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='تعديل يدوي'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
