# Generated by Django 6.0.3 on 2026-04-17 21:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(choices=[('b2b', 'B2B — للوكالات فقط'), ('b2b2c', 'B2B2C — للوكالات والعملاء النهائيين')], default='b2b', max_length=10, verbose_name='نوع الوكالة'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم المسؤول'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف المسؤول'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='منصب المسؤول'),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='agency',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الوكالة (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='owner_id_document',
            field=models.FileField(blank=True, null=True, upload_to='agencies/documents/id/', verbose_name='هوية المالك'),
        ),
        migrations.AddField(
            model_name='agency',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AddField(
            model_name='agency',
            name='tax_certificate',
            field=models.FileField(blank=True, null=True, upload_to='agencies/documents/tax/', verbose_name='الشهادة الضريبية'),
        ),
        migrations.AddField(
            model_name='agency',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='agencies/documents/trade/', verbose_name='الرخصة التجارية'),
        ),
        migrations.AddField(
            model_name='agency',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='currency',
            field=models.CharField(choices=[('MYR', 'Malaysian Ringgit'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SAR', 'Saudi Riyal'), ('AED', 'UAE Dirham'), ('SGD', 'Singapore Dollar')], default='MYR', max_length=3, verbose_name='العملة الافتراضية'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق للمراجعة'), ('active', 'نشط'), ('rejected', 'مرفوض'), ('suspended', 'موقوف')], db_index=True, default='pending', max_length=10, verbose_name='حالة الوكالة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدير عام'), ('admin', 'مشرف'), ('agency', 'وكالة شريكة'), ('supplier', 'مورد'), ('tourist', 'سائح')], default='tourist', max_length=20, verbose_name='الدور'),
        ),
        migrations.CreateModel(
            name='AgencyActivationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='رمز التفعيل')),
                ('is_used', models.BooleanField(default=False, verbose_name='مُستخدم')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation_token', to='accounts.agency', verbose_name='الوكالة')),
            ],
            options={
                'verbose_name': 'رمز تفعيل وكالة',
                'verbose_name_plural': 'رموز تفعيل الوكالات',
            },
        ),
    ]
