# Generated by Django 6.0.3 on 2026-04-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agency_agency_type_agency_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('code', models.CharField(max_length=6, verbose_name='الرمز')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='تاريخ الانتهاء')),
                ('used', models.BooleanField(default=False, verbose_name='مُستخدم')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'رمز دخول OTP',
                'verbose_name_plural': 'رموز الدخول OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='accounts_em_email_35a1ad_idx')],
            },
        ),
    ]
