# Generated by Django 6.0.3 on 2026-05-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'هذا البريد الإلكتروني مسجَّل بالفعل لوكالة.'}, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني'),
        ),
    ]
