# Generated by Django 6.0.3 on 2026-05-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_uid_authauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('ms', 'Bahasa Melayu')], default='ar', max_length=2, verbose_name='اللغة المفضلة'),
        ),
    ]
