# Generated by Django 6.0.3 on 2026-05-09 11:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0009_drop_airport_models_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gift', serialize=False, to='services.service', verbose_name='الخدمة')),
                ('subcategory', models.CharField(choices=[('sim_card', 'شريحة اتصال'), ('flowers', 'باقة ورد'), ('dates', 'تمر'), ('zam_zam', 'ماء زمزم'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الفئة الفرعية')),
                ('default_is_mandatory', models.BooleanField(default=False, help_text='إذا كانت true، تُضاف الهدية تلقائياً لكل باقة بحالة إجبارية', verbose_name='إجبارية افتراضياً')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر (MYR)')),
                ('currency', models.CharField(default='MYR', editable=False, max_length=3, verbose_name='العملة')),
                ('profit_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='نسبة الربح %')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'هدية',
                'verbose_name_plural': 'الهدايا',
                'db_table': 'gift',
                'ordering': ['subcategory', 'service__name'],
                'indexes': [models.Index(fields=['subcategory'], name='gift_subcate_14a37f_idx')],
            },
        ),
        migrations.CreateModel(
            name='GiftPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gifts/photos/%Y/%m/', verbose_name='الصورة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='تعليق')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gifts.gift', verbose_name='الهدية')),
            ],
            options={
                'db_table': 'gift_photo',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['gift', 'is_primary'], name='gift_photo_gift_id_13b8ed_idx')],
            },
        ),
    ]
