# Generated by Django 6.0.3 on 2026-03-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفندق')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('stars', models.IntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=3, verbose_name='النجوم')),
                ('description', models.TextField(blank=True, verbose_name='وصف الفندق')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='صورة الفندق')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='locations.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'فندق',
                'verbose_name_plural': 'الفنادق',
            },
        ),
    ]
