# Generated by Django 6.0.3 on 2026-04-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_commission_percentage_alter_hotel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/photos/%Y/%m/', verbose_name='الصورة')),
                ('is_primary', models.BooleanField(default=False, help_text='تظهر كأول صورة في صفحة الفندق', verbose_name='الصورة الرئيسية')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='تعليق على الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotels.hotel', verbose_name='الفندق')),
            ],
            options={
                'verbose_name': 'صورة فندق',
                'verbose_name_plural': 'صور الفنادق',
                'db_table': 'hotel_photo',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['hotel', 'is_primary'], name='hotel_photo_hotel_i_4ce591_idx'), models.Index(fields=['hotel', 'order'], name='hotel_photo_hotel_i_4eb315_idx')],
            },
        ),
    ]
