# Generated by Django 6.0.3 on 2026-05-09 15:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotelphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='default_margin_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='تستخدم كقيمة أولية لـ RoomRate.markup_pct عند الإنشاء (6-10% عادة)', max_digits=5, verbose_name='نسبة الربح الافتراضية %'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_chain',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Mercure, Holiday Inn, Ibis Style, Resort World, Thistle...', max_length=80, verbose_name='سلسلة الفنادق'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rate_currency',
            field=models.CharField(default='MYR', max_length=3, verbose_name='عملة كتيب الأسعار'),
        ),
    ]
