# Generated by Django 6.0.3 on 2026-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotel_default_margin_pct_hotel_hotel_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='الوصف بالعربية'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='الوصف بالإنجليزية'),
        ),
    ]
