# Generated by Django 6.0.3 on 2026-05-09 20:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_description_ar_hotel_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tax_per_night_per_room',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الضريبة لليلة الواحدة للغرفة الواحدة'),
        ),
    ]
