# Generated by Django 6.0.3 on 2026-05-11 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotel_tax_per_night_per_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=Decimal('3'), help_text='من 1 إلى 5، يدعم النصف نجمة (4.5)', max_digits=2, verbose_name='النجوم'),
        ),
    ]
