# Generated by Django 6.0.3 on 2026-03-31 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='وصف الفئة')),
            ],
            options={
                'verbose_name': 'فئة الخدمة',
                'verbose_name_plural': 'فئات الخدمات',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الخدمة')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الأساسي')),
                ('currency', models.CharField(default='MYR', max_length=3, verbose_name='العملة')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الخصم (%)')),
                ('breakfast_included', models.BooleanField(default=False, verbose_name='يشمل فطور / وجبات')),
                ('vehicle_type', models.CharField(blank=True, max_length=100, verbose_name='نوع المركبة (للنقل)')),
                ('max_participants', models.IntegerField(default=1, verbose_name='أقصى عدد مشاركين')),
                ('is_optional', models.BooleanField(default=True, verbose_name='خدمة اختيارية')),
                ('is_transfer', models.BooleanField(default=False, verbose_name='هل هي خدمة نقل؟')),
                ('relative_day', models.IntegerField(verbose_name='اليوم النسبي في الباقة')),
                ('category_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية حسب الفئة')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='locations.city', verbose_name='المدينة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['city__name', 'category__name', 'name'],
            },
        ),
    ]
