# Generated by Django 6.0.3 on 2026-04-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_breakfast_included_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الأساسي'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='relative_day',
            field=models.IntegerField(blank=True, help_text='فقط للخدمات المرتبطة بباقة. يُترك فارغاً للخدمات المستقلة.', null=True, verbose_name='اليوم النسبي في الباقة'),
        ),
    ]
