# Generated by Django 6.0.3 on 2026-04-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_base_price_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مثلاً 20.00 تعني 20% فوق سعر المورد', max_digits=5, null=True, verbose_name='نسبة عمولة الوكالة (%)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='نشطة'),
        ),
    ]
