# Generated by Django 6.0.3 on 2026-04-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_commission_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/photos/%Y/%m/', verbose_name='الصورة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='تعليق على الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'صورة خدمة',
                'verbose_name_plural': 'صور الخدمات',
                'db_table': 'service_photo',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['service', 'is_primary'], name='service_pho_service_10b531_idx'), models.Index(fields=['service', 'order'], name='service_pho_service_bdd06c_idx')],
            },
        ),
    ]
