# Generated by Django 6.0.3 on 2026-05-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, help_text='قائمة من {name, type, value} للخدمات المخصصة من المورد', verbose_name='حقول مخصصة'),
        ),
    ]
