# Generated by Django 6.0.3 on 2026-05-08 22:27 — manually trimmed
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_transfers', '0001_initial'),
    ]

    operations = [
        # نتجاوز RenameIndex لأن الـ index الأصلي لم يُنشأ في DB (state-only migration).
        # نتجاوز AlterField على Airport.id (لا تغيير حقيقي).
        migrations.AddField(
            model_name='airporttransfer',
            name='tour_guide_margin_pct',
            field=models.DecimalField(
                decimal_places=2, default=Decimal('10'),
                help_text='افتراضياً 10% — تُطبَّق على رسم المرشد عند تضمينه',
                max_digits=5, verbose_name='نسبة الربح على المرشد %',
            ),
        ),
    ]
