# Generated by Django 6.0.3 on 2026-04-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitywaitlist',
            name='api_credentials',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الوصول (مشفّرة لاحقاً)'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='api_endpoint',
            field=models.URLField(blank=True, verbose_name='رابط API (إن وُجد)'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='channel_name',
            field=models.CharField(blank=True, help_text='مثل: SiteMinder, Cloudbeds, Amadeus', max_length=100, verbose_name='اسم Channel Manager / النظام'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة ناجحة'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='sync_mode',
            field=models.CharField(choices=[('MANUAL', 'إدخال يدوي (WhatsApp/Excel)'), ('CHANNEL', 'Channel Manager (SiteMinder, Cloudbeds, ...)'), ('API', 'ربط مباشر بـ API'), ('GDS', 'GDS (Amadeus, Sabre, Hotelbeds)')], default='MANUAL', max_length=10, verbose_name='نمط التزامن'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='api_credentials',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الوصول (مشفّرة لاحقاً)'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='api_endpoint',
            field=models.URLField(blank=True, verbose_name='رابط API (إن وُجد)'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='channel_name',
            field=models.CharField(blank=True, help_text='مثل: SiteMinder, Cloudbeds, Amadeus', max_length=100, verbose_name='اسم Channel Manager / النظام'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة ناجحة'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='sync_mode',
            field=models.CharField(choices=[('MANUAL', 'إدخال يدوي (WhatsApp/Excel)'), ('CHANNEL', 'Channel Manager (SiteMinder, Cloudbeds, ...)'), ('API', 'ربط مباشر بـ API'), ('GDS', 'GDS (Amadeus, Sabre, Hotelbeds)')], default='MANUAL', max_length=10, verbose_name='نمط التزامن'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='api_credentials',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الوصول (مشفّرة لاحقاً)'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='api_endpoint',
            field=models.URLField(blank=True, verbose_name='رابط API (إن وُجد)'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='channel_name',
            field=models.CharField(blank=True, help_text='مثل: SiteMinder, Cloudbeds, Amadeus', max_length=100, verbose_name='اسم Channel Manager / النظام'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة ناجحة'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='sync_mode',
            field=models.CharField(choices=[('MANUAL', 'إدخال يدوي (WhatsApp/Excel)'), ('CHANNEL', 'Channel Manager (SiteMinder, Cloudbeds, ...)'), ('API', 'ربط مباشر بـ API'), ('GDS', 'GDS (Amadeus, Sabre, Hotelbeds)')], default='MANUAL', max_length=10, verbose_name='نمط التزامن'),
        ),
        migrations.AddField(
            model_name='propertywaitlist',
            name='api_credentials',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الوصول (مشفّرة لاحقاً)'),
        ),
        migrations.AddField(
            model_name='propertywaitlist',
            name='api_endpoint',
            field=models.URLField(blank=True, verbose_name='رابط API (إن وُجد)'),
        ),
        migrations.AddField(
            model_name='propertywaitlist',
            name='channel_name',
            field=models.CharField(blank=True, help_text='مثل: SiteMinder, Cloudbeds, Amadeus', max_length=100, verbose_name='اسم Channel Manager / النظام'),
        ),
        migrations.AddField(
            model_name='propertywaitlist',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة ناجحة'),
        ),
        migrations.AddField(
            model_name='propertywaitlist',
            name='sync_mode',
            field=models.CharField(choices=[('MANUAL', 'إدخال يدوي (WhatsApp/Excel)'), ('CHANNEL', 'Channel Manager (SiteMinder, Cloudbeds, ...)'), ('API', 'ربط مباشر بـ API'), ('GDS', 'GDS (Amadeus, Sabre, Hotelbeds)')], default='MANUAL', max_length=10, verbose_name='نمط التزامن'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='api_credentials',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الوصول (مشفّرة لاحقاً)'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='api_endpoint',
            field=models.URLField(blank=True, verbose_name='رابط API (إن وُجد)'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='channel_name',
            field=models.CharField(blank=True, help_text='مثل: SiteMinder, Cloudbeds, Amadeus', max_length=100, verbose_name='اسم Channel Manager / النظام'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة ناجحة'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='sync_mode',
            field=models.CharField(choices=[('MANUAL', 'إدخال يدوي (WhatsApp/Excel)'), ('CHANNEL', 'Channel Manager (SiteMinder, Cloudbeds, ...)'), ('API', 'ربط مباشر بـ API'), ('GDS', 'GDS (Amadeus, Sabre, Hotelbeds)')], default='MANUAL', max_length=10, verbose_name='نمط التزامن'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='api_credentials',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الوصول (مشفّرة لاحقاً)'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='api_endpoint',
            field=models.URLField(blank=True, verbose_name='رابط API (إن وُجد)'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='channel_name',
            field=models.CharField(blank=True, help_text='مثل: SiteMinder, Cloudbeds, Amadeus', max_length=100, verbose_name='اسم Channel Manager / النظام'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة ناجحة'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='sync_mode',
            field=models.CharField(choices=[('MANUAL', 'إدخال يدوي (WhatsApp/Excel)'), ('CHANNEL', 'Channel Manager (SiteMinder, Cloudbeds, ...)'), ('API', 'ربط مباشر بـ API'), ('GDS', 'GDS (Amadeus, Sabre, Hotelbeds)')], default='MANUAL', max_length=10, verbose_name='نمط التزامن'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='api_credentials',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الوصول (مشفّرة لاحقاً)'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='api_endpoint',
            field=models.URLField(blank=True, verbose_name='رابط API (إن وُجد)'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='channel_name',
            field=models.CharField(blank=True, help_text='مثل: SiteMinder, Cloudbeds, Amadeus', max_length=100, verbose_name='اسم Channel Manager / النظام'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة ناجحة'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='sync_mode',
            field=models.CharField(choices=[('MANUAL', 'إدخال يدوي (WhatsApp/Excel)'), ('CHANNEL', 'Channel Manager (SiteMinder, Cloudbeds, ...)'), ('API', 'ربط مباشر بـ API'), ('GDS', 'GDS (Amadeus, Sabre, Hotelbeds)')], default='MANUAL', max_length=10, verbose_name='نمط التزامن'),
        ),
    ]
