# Generated by Django 6.0.3 on 2026-04-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_activitywaitlist_api_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitywaitlist',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='ISO دولة'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='ISO دولة'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='ISO دولة'),
        ),
        migrations.AddField(
            model_name='propertywaitlist',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='propertywaitlist',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='ISO دولة'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='ISO دولة'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='ISO دولة'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='ISO دولة'),
        ),
    ]
