# Generated by Django 6.0.3 on 2026-04-29 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_amenities_hotel_check_in_time_and_more'),
        ('waitlist', '0003_activitywaitlist_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertywaitlist',
            name='created_hotel',
            field=models.OneToOneField(blank=True, help_text='يُملأ تلقائياً عند الموافقة على الطلب', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_waitlist', to='hotels.hotel', verbose_name='الفندق المُنشأ'),
        ),
    ]
