# Generated by Django 6.0.3 on 2026-04-29 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_phone_code'),
        ('waitlist', '0004_propertywaitlist_created_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertywaitlist',
            name='city_ref',
            field=models.ForeignKey(blank=True, help_text='يُحدَّد من قائمة منسدلة — لا يُكتب نصاً حراً', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_waitlist_entries', to='locations.city', verbose_name='المدينة (مرجع)'),
        ),
        migrations.AddField(
            model_name='propertywaitlist',
            name='country_ref',
            field=models.ForeignKey(blank=True, help_text='يُحدَّد من قائمة منسدلة — لا يُكتب نصاً حراً', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_waitlist_entries', to='locations.country', verbose_name='الدولة (مرجع)'),
        ),
    ]
