# Generated by Django 6.0.3 on 2026-04-29 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_phone_code'),
        ('services', '0002_remove_service_breakfast_included_and_more'),
        ('waitlist', '0005_propertywaitlist_city_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitywaitlist',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_waitlist_entries', to='locations.city', verbose_name='المدينة (مرجع)'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_waitlist_entries', to='locations.country', verbose_name='الدولة (مرجع)'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='created_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_activity_waitlist', to='services.service', verbose_name='الخدمة المُنشأة'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='currency',
            field=models.CharField(default='MYR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='min_group_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأدنى للأشخاص'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='price_per_group',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر النشاط للمجموعة'),
        ),
        migrations.AddField(
            model_name='activitywaitlist',
            name='price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر النشاط للشخص'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guide_waitlist_entries', to='locations.city', verbose_name='المدينة (مرجع)'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guide_waitlist_entries', to='locations.country', verbose_name='الدولة (مرجع)'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='created_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_guide_waitlist', to='services.service', verbose_name='الخدمة المُنشأة'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='currency',
            field=models.CharField(default='MYR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='price_full_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر اليوم الكامل'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='price_half_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر نصف يوم'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='price_hourly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الساعة'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الأساسي'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_waitlist_entries', to='locations.city', verbose_name='المدينة (مرجع)'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_waitlist_entries', to='locations.country', verbose_name='الدولة (مرجع)'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='created_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_other_waitlist', to='services.service', verbose_name='الخدمة المُنشأة'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='currency',
            field=models.CharField(default='MYR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('person', 'لكل شخص'), ('hour', 'لكل ساعة'), ('day', 'لكل يوم'), ('unit', 'لكل قطعة'), ('group', 'للمجموعة')], default='person', max_length=20, verbose_name='وحدة التسعير'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='pricing_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات التسعير'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_waitlist_entries', to='locations.city', verbose_name='المدينة (مرجع)'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_waitlist_entries', to='locations.country', verbose_name='الدولة (مرجع)'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='created_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_restaurant_waitlist', to='services.service', verbose_name='الخدمة المُنشأة'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='currency',
            field=models.CharField(default='MYR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='متوسط سعر الوجبة للشخص'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='price_set_menu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر القائمة الثابتة'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_waitlist_entries', to='locations.city', verbose_name='المدينة (مرجع)'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_waitlist_entries', to='locations.country', verbose_name='الدولة (مرجع)'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='created_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_transport_waitlist', to='services.service', verbose_name='الخدمة المُنشأة'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='currency',
            field=models.CharField(default='MYR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='price_airport_transfer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر نقل المطار'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='price_full_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر اليوم الكامل'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='price_hourly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الساعة'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='price_intercity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الرحلة بين المدن'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wellness_waitlist_entries', to='locations.city', verbose_name='المدينة (مرجع)'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wellness_waitlist_entries', to='locations.country', verbose_name='الدولة (مرجع)'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='created_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_wellness_waitlist', to='services.service', verbose_name='الخدمة المُنشأة'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='currency',
            field=models.CharField(default='MYR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='price_package',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الباقة'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='price_per_session',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الجلسة'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='session_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الجلسة (دقيقة)'),
        ),
    ]
