# Generated by Django 6.0.3 on 2026-04-30 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('waitlist', '0006_activitywaitlist_city_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(verbose_name='معرّف الطلب')),
                ('image', models.ImageField(upload_to='waitlist/photos/%Y/%m/', verbose_name='الصورة')),
                ('is_primary', models.BooleanField(default=False, help_text='الصورة الأولى التي تظهر للسائح', verbose_name='الصورة الرئيسية')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 = الأول', verbose_name='ترتيب العرض')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='تعليق على الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع الطلب')),
            ],
            options={
                'verbose_name': 'صورة طلب',
                'verbose_name_plural': 'صور الطلبات',
                'db_table': 'waitlist_photo',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='waitlist_ph_content_e15f34_idx'), models.Index(fields=['content_type', 'object_id', 'is_primary'], name='waitlist_ph_content_aa4e11_idx')],
            },
        ),
    ]
