# Generated by Django 6.0.3 on 2026-04-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0007_waitlistphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitywaitlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='guidewaitlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='propertywaitlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='restaurantwaitlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='wellnesswaitlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
    ]
