# Generated by Django 6.0.3 on 2026-05-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0008_add_description_to_waitlistbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, help_text='قائمة من {name, type, value} — type ∈ [text, number, date, select, boolean]', verbose_name='حقول مخصصة'),
        ),
        migrations.AddField(
            model_name='otherservicewaitlist',
            name='proposed_category_name',
            field=models.CharField(blank=True, help_text='اسم نوع الخدمة الذي يقترحه المورد إن لم يجد فئة مناسبة', max_length=100, verbose_name='اسم الفئة المقترحة'),
        ),
    ]
