# Generated by Django 6.0.3 on 2026-03-31 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الباقة')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('description', models.TextField(verbose_name='وصف الباقة')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الأساسي')),
                ('currency', models.CharField(default='MYR', max_length=3, verbose_name='العملة')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الخصم (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='صورة الباقة')),
                ('highlights', models.TextField(blank=True, verbose_name='المميزات الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='الباقة نشطة')),
            ],
            options={
                'verbose_name': 'باقة سياحية',
                'verbose_name_plural': 'الباقات السياحية',
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر مخصص')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='الخدمة')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='packages.tourpackage')),
            ],
            options={
                'verbose_name': 'خدمة داخل الباقة',
                'verbose_name_plural': 'الخدمات داخل الباقة',
                'unique_together': {('package', 'service')},
            },
        ),
        migrations.CreateModel(
            name='PackageHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights', models.PositiveIntegerField(default=1, verbose_name='عدد الليالي')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel', verbose_name='الفندق')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='packages.tourpackage')),
            ],
            options={
                'verbose_name': 'فندق داخل الباقة',
                'verbose_name_plural': 'الفنادق داخل الباقة',
                'unique_together': {('package', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='PackageCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights', models.PositiveIntegerField(default=1, verbose_name='عدد الليالي')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='المدينة')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='packages.tourpackage')),
            ],
            options={
                'verbose_name': 'مدينة داخل الباقة',
                'verbose_name_plural': 'المدن داخل الباقة',
                'unique_together': {('package', 'city')},
            },
        ),
    ]
