# Generated by Django 6.0.3 on 2026-03-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('packages', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packageservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packageservice',
            name='service',
        ),
        migrations.CreateModel(
            name='PackageCityHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights', models.PositiveIntegerField(default=1, verbose_name='عدد الليالي')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel', verbose_name='الفندق')),
                ('package_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='packages.packagecity')),
            ],
            options={
                'verbose_name': 'فندق في مدينة',
                'verbose_name_plural': 'الفنادق في المدن',
                'unique_together': {('package_city', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='PackageCityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر مخصص')),
                ('package_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='packages.packagecity')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة في مدينة',
                'verbose_name_plural': 'الخدمات في المدن',
                'unique_together': {('package_city', 'service')},
            },
        ),
        migrations.DeleteModel(
            name='PackageHotel',
        ),
        migrations.DeleteModel(
            name='PackageService',
        ),
    ]
