# Generated by Django 6.0.3 on 2026-05-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
        ('packages', '0004_packageflight_profit_margin_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='gift',
            field=models.ForeignKey(blank=True, help_text='كل باقة تحتاج هدية افتراضية تُضاف لكل حجز', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='gifts.gift', verbose_name='الهدية الإجبارية'),
        ),
    ]
