# Generated by Django 6.0.3 on 2026-05-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_transfers', '0004_descriptions_and_photos'),
        ('flights', '0001_initial'),
        ('hotels', '0010_alter_hotel_stars'),
        ('packages', '0005_custompackage_gift'),
        ('tours_excursions', '0005_tour_description_ar_tour_description_en_tourphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='allowed_flight_routes',
            field=models.ManyToManyField(blank=True, help_text='مسارات الطيران الداخلي/الدولي المسموحة (Duffel)', related_name='packages_allowed_in', to='flights.flightroute', verbose_name='مسارات الطيران المسموحة'),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='allowed_tours',
            field=models.ManyToManyField(blank=True, help_text='الجولات التي يستطيع الزبون اختيارها (مفلترة حسب مدن الباقة)', related_name='packages_allowed_in', to='tours_excursions.tour', verbose_name='الجولات المسموحة'),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='allowed_transfers',
            field=models.ManyToManyField(blank=True, help_text='نقل المطار + بين المدن المسموحة لاختيار الزبون', related_name='packages_allowed_in', to='airport_transfers.airporttransfer', verbose_name='خدمات النقل المسموحة'),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='is_template',
            field=models.BooleanField(default=False, help_text='عند تفعيلها تظهر للوكالات الجزائرية في لوحاتها', verbose_name='قالب منشور للوكالات'),
        ),
        migrations.AddField(
            model_name='packagecity',
            name='allowed_hotels',
            field=models.ManyToManyField(blank=True, help_text='الفنادق التي يستطيع الزبون الاختيار منها في هذه المدينة', related_name='package_cities_allowed_in', to='hotels.hotel', verbose_name='الفنادق المسموحة في هذه المدينة'),
        ),
        migrations.AlterField(
            model_name='packagecity',
            name='nights',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الليالي الافتراضي'),
        ),
    ]
