# Generated by Django 6.0.3 on 2026-05-09 15:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0006_hotel_default_margin_pct_hotel_hotel_chain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم الموسم')),
                ('season_type', models.CharField(choices=[('flat', 'سعر ثابت'), ('low', 'موسم منخفض'), ('shoulder', 'موسم متوسط'), ('normal', 'عادي'), ('high', 'موسم مرتفع'), ('peak', 'ذروة'), ('super_peak', 'ذروة قصوى'), ('tactical_promo', 'عرض تكتيكي')], default='flat', max_length=20, verbose_name='نوع الموسم')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_seasons', to='hotels.hotel', verbose_name='الفندق')),
            ],
            options={
                'verbose_name': 'موسم فندق',
                'verbose_name_plural': 'مواسم الفنادق',
                'db_table': 'hotel_rates_season',
                'ordering': ['hotel', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelSeasonDateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('label', models.CharField(blank=True, default='', max_length=60, verbose_name='تسمية النطاق')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_ranges', to='hotel_rates.hotelseason', verbose_name='الموسم')),
            ],
            options={
                'verbose_name': 'نطاق تاريخي للموسم',
                'verbose_name_plural': 'نطاقات تاريخية للمواسم',
                'db_table': 'hotel_rates_season_date_range',
                'ordering': ['season', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الفئة')),
                ('name_ar', models.CharField(blank=True, default='', max_length=120, verbose_name='الاسم بالعربية')),
                ('base_type', models.CharField(choices=[('room', 'غرفة'), ('suite', 'جناح'), ('villa', 'فيلا'), ('chalet', 'شاليه'), ('apartment', 'شقة'), ('bungalow', 'بنغلو'), ('package', 'باقة')], default='room', max_length=20, verbose_name='النوع الأساسي')),
                ('view_type', models.CharField(choices=[('standard', 'قياسي'), ('sea', 'إطلالة بحر'), ('hill', 'إطلالة تل'), ('garden', 'إطلالة حديقة'), ('pool', 'إطلالة مسبح'), ('city', 'إطلالة مدينة'), ('klcc', 'إطلالة KLCC'), ('kl_tower', 'إطلالة برج كوالالمبور'), ('beach', 'إطلالة شاطئ'), ('lagoon', 'إطلالة بحيرة'), ('beachfront', 'مواجه للشاطئ'), ('runaway', 'إطلالة ممر'), ('street', 'إطلالة شارع'), ('other', 'أخرى')], default='standard', max_length=20, verbose_name='نوع الإطلالة')),
                ('view_custom', models.CharField(blank=True, default='', max_length=80, verbose_name='إطلالة مخصصة')),
                ('pax', models.PositiveSmallIntegerField(default=2, verbose_name='عدد الأشخاص')),
                ('max_occupancy', models.PositiveSmallIntegerField(default=2, verbose_name='أقصى إشغال')),
                ('bed_config', models.CharField(blank=True, default='', max_length=60, verbose_name='تركيب الأسرّة')),
                ('is_package', models.BooleanField(default=False, verbose_name='باقة شاملة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_categories/%Y/%m/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='hotels.hotel', verbose_name='الفندق')),
            ],
            options={
                'verbose_name': 'فئة غرفة',
                'verbose_name_plural': 'فئات الغرف',
                'db_table': 'hotel_rates_room_category',
                'ordering': ['hotel', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='التسمية')),
                ('surcharge_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة مئوية')], default='fixed', max_length=12, verbose_name='نوع الرسم')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ / النسبة')),
                ('weekday', models.SmallIntegerField(blank=True, choices=[(0, 'الإثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], null=True, verbose_name='يوم الأسبوع')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='من تاريخ')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='إلى تاريخ')),
                ('applies_to_tier', models.CharField(blank=True, choices=[('fit', 'FIT'), ('fit_normal', 'FIT — Normal'), ('fit_promo', 'FIT — Promo'), ('git', 'GIT'), ('git_normal', 'GIT — Normal'), ('git_series', 'GIT — Series')], default='', max_length=20, verbose_name='ينطبق على طبقة')),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='hotels.hotel', verbose_name='الفندق')),
                ('room_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='hotel_rates.roomcategory', verbose_name='فئة غرفة')),
            ],
            options={
                'verbose_name': 'رسم إضافي',
                'verbose_name_plural': 'الرسوم الإضافية',
                'db_table': 'hotel_rates_surcharge',
                'ordering': ['hotel', 'date_start', 'weekday'],
            },
        ),
        migrations.CreateModel(
            name='RoomInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160, verbose_name='التسمية')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='الكمية')),
                ('unit', models.CharField(choices=[('pax', 'شخص'), ('night', 'ليلة'), ('piece', 'قطعة'), ('voucher', 'قسيمة'), ('other', 'أخرى')], default='pax', max_length=10, verbose_name='الوحدة')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='hotel_rates.roomcategory', verbose_name='فئة الغرفة')),
            ],
            options={
                'verbose_name': 'محتوى باقة',
                'verbose_name_plural': 'محتويات الباقات',
                'db_table': 'hotel_rates_room_inclusion',
                'ordering': ['room_category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_tier', models.CharField(choices=[('fit', 'FIT'), ('fit_normal', 'FIT — Normal'), ('fit_promo', 'FIT — Promo'), ('git', 'GIT'), ('git_normal', 'GIT — Normal'), ('git_series', 'GIT — Series')], db_index=True, default='fit', max_length=20, verbose_name='طبقة التسعير')),
                ('day_type', models.CharField(choices=[('all', 'كل الأيام'), ('weekday', 'أيام الأسبوع'), ('weekend', 'عطلة نهاية الأسبوع')], default='all', max_length=10, verbose_name='نوع اليوم')),
                ('occupancy', models.CharField(choices=[('single', 'فردي'), ('double', 'زوجي'), ('triple', 'ثلاثي'), ('quad', 'رباعي')], default='double', max_length=10, verbose_name='الإشغال')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الأساسي لليلة')),
                ('rate_with_breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر مع الإفطار')),
                ('extra_bed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر سرير إضافي')),
                ('kid_breakfast_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر فطور طفل')),
                ('kid_breakfast_free', models.BooleanField(default=False, verbose_name='فطور أطفال مجاني')),
                ('kid_breakfast_age_limit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الحد العمري للمجانية')),
                ('tax_inclusive', models.BooleanField(default=True, verbose_name='يشمل الضريبة')),
                ('markup_pct', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='نسبة الربح %')),
                ('currency', models.CharField(default='MYR', max_length=3, verbose_name='العملة')),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='hotel_rates.roomcategory', verbose_name='فئة الغرفة')),
                ('season', models.ForeignKey(blank=True, help_text='NULL = سعر ثابت طوال السنة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='hotel_rates.hotelseason', verbose_name='الموسم')),
            ],
            options={
                'verbose_name': 'تسعيرة غرفة',
                'verbose_name_plural': 'تسعيرات الغرف',
                'db_table': 'hotel_rates_room_rate',
                'ordering': ['room_category', 'season', 'pricing_tier', 'day_type', 'occupancy'],
            },
        ),
        migrations.AddIndex(
            model_name='hotelseason',
            index=models.Index(fields=['hotel', 'season_type'], name='hotel_rates_hotel_i_c81c68_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelseason',
            index=models.Index(fields=['hotel', 'is_active'], name='hotel_rates_hotel_i_b8cfee_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotelseason',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_season_name_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='hotelseasondaterange',
            index=models.Index(fields=['season', 'start_date', 'end_date'], name='hotel_rates_season__47b1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelseasondaterange',
            index=models.Index(fields=['start_date', 'end_date'], name='hotel_rates_start_d_b81ab3_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotelseasondaterange',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='season_range_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='roomcategory',
            index=models.Index(fields=['hotel', 'is_active'], name='hotel_rates_hotel_i_546f05_idx'),
        ),
        migrations.AddIndex(
            model_name='roomcategory',
            index=models.Index(fields=['hotel', 'base_type'], name='hotel_rates_hotel_i_188a98_idx'),
        ),
        migrations.AddIndex(
            model_name='roomcategory',
            index=models.Index(fields=['hotel', 'view_type'], name='hotel_rates_hotel_i_8b4e6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomcategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'name', 'view_type', 'pax'), name='uniq_room_category_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='hotelsurcharge',
            index=models.Index(fields=['hotel', 'is_active'], name='hotel_rates_hotel_i_5680bf_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelsurcharge',
            index=models.Index(fields=['hotel', 'weekday'], name='hotel_rates_hotel_i_b91dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelsurcharge',
            index=models.Index(fields=['date_start', 'date_end'], name='hotel_rates_date_st_05c0c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotelsurcharge',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__isnull', False), ('date_start__isnull', False), _connector='OR'), name='surcharge_must_have_weekday_or_date'),
        ),
        migrations.AddConstraint(
            model_name='hotelsurcharge',
            constraint=models.CheckConstraint(condition=models.Q(('date_end__isnull', True), ('date_start__isnull', True), ('date_end__gte', models.F('date_start')), _connector='OR'), name='surcharge_date_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='roominclusion',
            index=models.Index(fields=['room_category'], name='hotel_rates_room_ca_79ba33_idx'),
        ),
        migrations.AddIndex(
            model_name='roomrate',
            index=models.Index(fields=['room_category', 'season', 'pricing_tier'], name='hotel_rates_room_ca_a3fe3e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomrate',
            index=models.Index(fields=['room_category', 'is_active'], name='hotel_rates_room_ca_5e2cef_idx'),
        ),
        migrations.AddIndex(
            model_name='roomrate',
            index=models.Index(fields=['pricing_tier', 'day_type'], name='hotel_rates_pricing_49b9de_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomrate',
            constraint=models.UniqueConstraint(fields=('room_category', 'season', 'pricing_tier', 'day_type', 'occupancy'), name='uniq_rate_matrix_cell'),
        ),
        migrations.AddConstraint(
            model_name='roomrate',
            constraint=models.CheckConstraint(condition=models.Q(('base_rate__gte', 0)), name='rate_base_non_negative'),
        ),
    ]
