# Generated by Django 6.0.3 on 2026-05-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomrate',
            name='uniq_rate_matrix_cell',
        ),
        migrations.AddConstraint(
            model_name='roomrate',
            constraint=models.UniqueConstraint(condition=models.Q(('season__isnull', False)), fields=('room_category', 'season', 'pricing_tier', 'day_type', 'occupancy'), name='uniq_rate_matrix_cell_seasonal'),
        ),
        migrations.AddConstraint(
            model_name='roomrate',
            constraint=models.UniqueConstraint(condition=models.Q(('season__isnull', True)), fields=('room_category', 'pricing_tier', 'day_type', 'occupancy'), name='uniq_rate_matrix_cell_flat'),
        ),
    ]
