# Generated by Django 6.0.3 on 2026-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rates', '0002_remove_roomrate_uniq_rate_matrix_cell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrate',
            name='child_with_bed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر طفل بسرير'),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='child_without_bed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر طفل بدون سرير'),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='infant_bed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر سرير الرضيع'),
        ),
    ]
