# Generated by Django 6.0.3 on 2026-05-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rates', '0003_roomrate_child_with_bed_price_and_more'),
        ('hotels', '0008_hotel_tax_per_night_per_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='child_no_bed_age_from',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='عمر طفل بدون سرير من'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='child_no_bed_age_to',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='عمر طفل بدون سرير إلى'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='child_with_bed_age_from',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='عمر طفل بسرير من'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='child_with_bed_age_to',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='عمر طفل بسرير إلى'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='infant_age_from',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عمر الرضيع من'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='infant_age_to',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='عمر الرضيع إلى'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='quantity_in_hotel',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الغرف من هذا النوع في الفندق'),
        ),
        migrations.CreateModel(
            name='PricingTierDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('fit', 'FIT'), ('fit_normal', 'FIT — Normal'), ('fit_promo', 'FIT — Promo'), ('git', 'GIT'), ('git_normal', 'GIT — Normal'), ('git_series', 'GIT — Series')], help_text='يجب أن يطابق RoomRate.pricing_tier', max_length=20, verbose_name='رمز الطبقة')),
                ('label', models.CharField(blank=True, default='', help_text='اختياري — اسم بديل يظهر في الواجهة', max_length=80, verbose_name='تسمية مخصصة')),
                ('min_rooms_required', models.PositiveIntegerField(default=0, verbose_name='عدد الغرف اللازم لتطبيق الطبقة')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tier_defs', to='hotels.hotel', verbose_name='الفندق')),
            ],
            options={
                'verbose_name': 'طبقة تسعير',
                'verbose_name_plural': 'طبقات التسعير',
                'db_table': 'hotel_rates_pricing_tier_def',
                'ordering': ['hotel', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'code'), name='uniq_tier_def_per_hotel')],
            },
        ),
    ]
