# Generated by Django 6.0.3 on 2026-05-09 22:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rates', '0004_roomcategory_child_no_bed_age_from_and_more'),
        ('hotels', '0008_hotel_tax_per_night_per_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelGuestPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_bed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر سرير إضافي')),
                ('infant_age_from', models.PositiveSmallIntegerField(default=0, verbose_name='عمر الرضيع من')),
                ('infant_age_to', models.PositiveSmallIntegerField(default=2, verbose_name='عمر الرضيع إلى')),
                ('infant_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الرضيع')),
                ('child_with_bed_age_from', models.PositiveSmallIntegerField(default=7, verbose_name='عمر طفل بسرير من')),
                ('child_with_bed_age_to', models.PositiveSmallIntegerField(default=12, verbose_name='عمر طفل بسرير إلى')),
                ('child_with_bed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر طفل بسرير')),
                ('child_no_bed_age_from', models.PositiveSmallIntegerField(default=3, verbose_name='عمر طفل بدون سرير من')),
                ('child_no_bed_age_to', models.PositiveSmallIntegerField(default=6, verbose_name='عمر طفل بدون سرير إلى')),
                ('child_no_bed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر طفل بدون سرير')),
                ('child_breakfast_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر فطور الأطفال')),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تسعيرة ضيوف',
                'verbose_name_plural': 'تسعيرات الضيوف',
                'db_table': 'hotel_rates_guest_pricing',
                'ordering': ['hotel', 'tier'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricingtierdef',
            options={'ordering': ['hotel', 'sort_order', 'name'], 'verbose_name': 'طبقة تسعير', 'verbose_name_plural': 'طبقات التسعير'},
        ),
        migrations.RemoveConstraint(
            model_name='pricingtierdef',
            name='uniq_tier_def_per_hotel',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='child_no_bed_age_from',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='child_no_bed_age_to',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='child_with_bed_age_from',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='child_with_bed_age_to',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='infant_age_from',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='infant_age_to',
        ),
        migrations.AddField(
            model_name='pricingtierdef',
            name='name',
            field=models.CharField(default='', help_text='يدخل يدوياً (FIT, GIT, Premium...)', max_length=80, verbose_name='اسم الطبقة'),
        ),
        migrations.AddField(
            model_name='pricingtierdef',
            name='profit_margin_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=5, verbose_name='هامش الربح % لهذه الطبقة'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='max_child_beds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='أقصى عدد أسرّة أطفال'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='max_extra_beds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='أقصى عدد أسرّة إضافية'),
        ),
        migrations.AlterField(
            model_name='roomrate',
            name='pricing_tier',
            field=models.CharField(db_index=True, default='fit', help_text='اسم الطبقة كما هو في PricingTierDef.name (نص حر)', max_length=80, verbose_name='طبقة التسعير'),
        ),
        migrations.AddConstraint(
            model_name='pricingtierdef',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_tier_def_per_hotel'),
        ),
        migrations.AddField(
            model_name='hotelguestpricing',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_pricing', to='hotels.hotel', verbose_name='الفندق'),
        ),
        migrations.AddField(
            model_name='hotelguestpricing',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_pricing', to='hotel_rates.pricingtierdef', verbose_name='طبقة التسعير'),
        ),
        migrations.RemoveField(
            model_name='pricingtierdef',
            name='code',
        ),
        migrations.RemoveField(
            model_name='pricingtierdef',
            name='label',
        ),
        migrations.AddConstraint(
            model_name='hotelguestpricing',
            constraint=models.UniqueConstraint(fields=('hotel', 'tier'), name='uniq_guest_pricing_per_tier'),
        ),
    ]
