# Generated by Django 6.0.3 on 2026-05-10 14:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rates', '0005_hotelguestpricing_alter_pricingtierdef_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelguestpricing',
            name='child_breakfast_age_from',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='عمر فطور الطفل من'),
        ),
        migrations.AddField(
            model_name='hotelguestpricing',
            name='child_breakfast_age_to',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='عمر فطور الطفل إلى'),
        ),
        migrations.AddField(
            model_name='pricingtierdef',
            name='max_rooms_required',
            field=models.PositiveIntegerField(blank=True, help_text='اتركها فارغة إذا لم يكن هناك حد أقصى', null=True, verbose_name='تنتهي عند عدد الغرف'),
        ),
        migrations.AlterField(
            model_name='pricingtierdef',
            name='min_rooms_required',
            field=models.PositiveIntegerField(default=0, verbose_name='تبدأ من عدد الغرف'),
        ),
        migrations.AlterField(
            model_name='pricingtierdef',
            name='profit_margin_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=5, verbose_name='نسبة العمولة %'),
        ),
    ]
