# Generated by Django 6.0.3 on 2026-05-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rates', '0006_hotelguestpricing_child_breakfast_age_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_category_photos/%Y/%m/', verbose_name='الصورة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='رئيسية')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='التعليق')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotel_rates.roomcategory', verbose_name='فئة الغرفة')),
            ],
            options={
                'verbose_name': 'صورة فئة غرفة',
                'verbose_name_plural': 'صور فئات الغرف',
                'db_table': 'hotel_rates_room_category_photo',
                'ordering': ['room_category', '-is_primary', 'order'],
                'indexes': [models.Index(fields=['room_category', 'is_primary'], name='hotel_rates_room_ca_80b099_idx'), models.Index(fields=['room_category', 'order'], name='hotel_rates_room_ca_c52235_idx')],
            },
        ),
    ]
