# Generated by Django 6.0.3 on 2026-05-02 01:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0005_hotelphoto'),
        ('services', '0005_servicephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ms', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('target_audience', models.CharField(choices=[('tourist', 'Tourist'), ('partner', 'Partner Agency'), ('supplier', 'Supplier'), ('all', 'All')], default='all', max_length=10)),
                ('color', models.CharField(default='#FF6B35', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'db_table': 'blog_category',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_ms', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'db_table': 'blog_tag',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='HTML sanitized via bleach')),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=10)),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('ms', 'Bahasa Melayu')], default='en', max_length=2)),
                ('translation_group', models.UUIDField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='blog/og/')),
                ('read_time', models.PositiveSmallIntegerField(default=0, help_text='In minutes')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_post',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_revisions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Revision',
                'db_table': 'blog_revision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogRelatedHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_mentions', to='hotels.hotel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_hotels', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog → Hotel',
                'db_table': 'blog_related_hotel',
                'ordering': ['order', 'id'],
                'unique_together': {('post', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='BlogRelatedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_services', to='blog.blogpost')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_mentions', to='services.service')),
            ],
            options={
                'verbose_name': 'Blog → Service',
                'db_table': 'blog_related_service',
                'ordering': ['order', 'id'],
                'unique_together': {('post', 'service')},
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'language', '-published_at'], name='blog_post_status_92ab3b_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', '-published_at'], name='blog_post_is_feat_7251c7_idx'),
        ),
    ]
