# Generated by Django 6.0.3 on 2026-04-30 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('location', models.CharField(max_length=100, verbose_name='البلد/المدينة')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='كود الدولة (مثل: SA, MY, AE)')),
                ('text', models.JSONField(default=dict, help_text='{"ar": "...", "en": "...", "ms": "..."}', verbose_name='الرأي (3 لغات)')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='التقييم (1-5)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='الصورة الشخصية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رأي عميل',
                'verbose_name_plural': 'آراء العملاء',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.JSONField(default=dict, help_text='{"ar": "...", "en": "...", "ms": "..."}', verbose_name='شارة Hero (3 لغات)')),
                ('hero_title', models.JSONField(default=dict, verbose_name='عنوان Hero')),
                ('hero_title_highlight', models.JSONField(default=dict, verbose_name='الكلمة المُميَّزة في العنوان')),
                ('hero_subtitle', models.JSONField(default=dict, verbose_name='عنوان فرعي Hero')),
                ('search_placeholder', models.JSONField(default=dict, verbose_name='نص البحث الافتراضي')),
                ('stats_visible', models.BooleanField(default=True, verbose_name='إظهار شريط الإحصائيات')),
                ('stats_customers', models.PositiveIntegerField(default=2400, verbose_name='عدد العملاء (ك)')),
                ('stats_destinations', models.PositiveIntegerField(default=15, verbose_name='عدد الوجهات')),
                ('stats_suppliers', models.PositiveIntegerField(default=120, verbose_name='عدد الموردين')),
                ('stats_partners', models.PositiveIntegerField(default=50, verbose_name='عدد الوكالات الشريكة')),
                ('show_destinations', models.BooleanField(default=True, verbose_name='إظهار الوجهات')),
                ('show_hotels', models.BooleanField(default=True, verbose_name='إظهار الفنادق')),
                ('show_services', models.BooleanField(default=True, verbose_name='إظهار الخدمات')),
                ('show_trust_section', models.BooleanField(default=True, verbose_name='إظهار قسم الثقة')),
                ('show_testimonials', models.BooleanField(default=True, verbose_name='إظهار آراء العملاء')),
                ('show_supplier_cta', models.BooleanField(default=True, verbose_name='إظهار CTA المورد')),
                ('show_categories', models.BooleanField(default=True, verbose_name='إظهار شريط الفئات')),
                ('hotels_limit', models.PositiveSmallIntegerField(default=8, verbose_name='عدد الفنادق المعروضة')),
                ('services_limit', models.PositiveSmallIntegerField(default=8, verbose_name='عدد الخدمات المعروضة')),
                ('trust_badge_1_title', models.JSONField(blank=True, default=dict)),
                ('trust_badge_1_subtitle', models.JSONField(blank=True, default=dict)),
                ('trust_badge_2_title', models.JSONField(blank=True, default=dict)),
                ('trust_badge_2_subtitle', models.JSONField(blank=True, default=dict)),
                ('trust_badge_3_title', models.JSONField(blank=True, default=dict)),
                ('trust_badge_3_subtitle', models.JSONField(blank=True, default=dict)),
                ('trust_badge_4_title', models.JSONField(blank=True, default=dict)),
                ('trust_badge_4_subtitle', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات الصفحة الرئيسية',
                'verbose_name_plural': 'إعدادات الصفحة الرئيسية',
            },
        ),
    ]
