# Generated by Django 6.0.3 on 2026-05-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_testimonial_homepageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict, help_text='{"ar": "كوالالمبور", "en": "Kuala Lumpur", "ms": "Kuala Lumpur"}', verbose_name='اسم الوجهة (3 لغات)')),
                ('image', models.ImageField(help_text='يُفضّل 800×600 أو أكبر', upload_to='destinations/', verbose_name='صورة الوجهة')),
                ('city_name', models.CharField(help_text='يُطابق City.name (case-insensitive). مثل: Kuala Lumpur', max_length=100, verbose_name='اسم المدينة (للفلترة)')),
                ('country_code', models.CharField(blank=True, help_text='مثل: MY — يُضيّق الفلتر للدولة', max_length=2, verbose_name='كود الدولة (اختياري)')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='الأقل = يظهر أولاً', verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('size', models.CharField(choices=[('large', 'كبير (يأخذ نصف الشبكة)'), ('medium', 'متوسط'), ('small', 'صغير')], default='medium', max_length=10, verbose_name='حجم البطاقة في الشبكة')),
                ('description', models.JSONField(blank=True, default=dict, help_text='{"ar": "...", "en": "...", "ms": "..."}', verbose_name='وصف الوجهة (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'وجهة',
                'verbose_name_plural': 'الوجهات',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
