# Generated by Django 6.0.3 on 2026-05-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_phone_code'),
        ('settings_app', '0003_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(blank=True, help_text='المدينة المرتبطة (يُفلتر بها الفنادق والخدمات)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='locations.city', verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم المدينة (legacy)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='كود الدولة (legacy)'),
        ),
    ]
