# Generated by Django 6.0.3 on 2026-05-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_destination_city_alter_destination_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(default='MYR', max_length=3, verbose_name='العملة الافتراضية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_hq_commission_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='عمولة HQ الافتراضية %'),
        ),
    ]
