# Generated by Django 6.0.3 on 2026-04-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-population', 'name'], 'verbose_name': 'مدينة', 'verbose_name_plural': 'المدن'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name_ar', 'name'], 'verbose_name': 'دولة', 'verbose_name_plural': 'الدول'},
        ),
        migrations.AddField(
            model_name='city',
            name='admin1',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة الإدارية'),
        ),
        migrations.AddField(
            model_name='city',
            name='geoname_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='GeoNames ID'),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ar',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='الاسم بالعربية'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(db_index=True, default=0, verbose_name='عدد السكان'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=50, verbose_name='القارة'),
        ),
        migrations.AddField(
            model_name='country',
            name='geoname_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='GeoNames ID'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='رمز ISO 2'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, verbose_name='رمز ISO 3'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاسم بالعربية'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='رمز الهاتف'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='اسم المدينة'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'name'], name='locations_c_country_a5360f_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name_ar'], name='locations_c_name_ar_a3b7d1_idx'),
        ),
    ]
