# Generated by Django 6.0.3 on 2026-04-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_options_alter_country_options_city_admin1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='رمز الهاتف'),
        ),
    ]
