# Generated by Django 6.0.3 on 2026-03-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_city_slug_remove_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='صورة المدينة'),
        ),
    ]
