# Generated by Django 6.0.3 on 2026-04-16 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_fr', models.CharField(blank=True, max_length=100)),
                ('name_ms', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('GENERAL', 'عام'), ('FOOD', 'طعام وشراب'), ('WELLNESS', 'صحة وعافية'), ('TRANSPORT', 'نقل'), ('BUSINESS', 'أعمال'), ('OUTDOOR', 'خارجي'), ('ENTERTAINMENT', 'ترفيه'), ('FAMILY', 'عائلي'), ('SAFETY', 'أمان'), ('ACCESSIBILITY', 'إمكانية الوصول')], max_length=20)),
                ('amenity_type', models.CharField(choices=[('HOTEL_ONLY', 'للفنادق فقط'), ('ALL', 'للجميع')], default='HOTEL_ONLY', max_length=15)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'hotel_amenity',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HotelPricePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('STANDARD', 'قياسي'), ('NON_REFUNDABLE', 'غير قابل للاسترداد'), ('WEEKLY', 'أسبوعي')], default='STANDARD', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='النسبة المئوية للخصم عن السعر القياسي', max_digits=5)),
                ('min_nights', models.PositiveSmallIntegerField(default=1, help_text='الحد الأدنى للليالي لتطبيق هذه الخطة')),
                ('cancellation_free_days', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotel_price_plan',
            },
        ),
        migrations.CreateModel(
            name='HotelPropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hotel_property_amenity',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING_REVIEW', 'بانتظار المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=20)),
                ('room_unit_type', models.CharField(choices=[('TWIN', 'توأم (Twin)'), ('DOUBLE', 'مزدوج (Double)'), ('SINGLE', 'مفرد (Single)'), ('TRIPLE', 'ثلاثي (Triple)'), ('QUAD', 'رباعي (Quad)'), ('SUITE', 'جناح (Suite)'), ('JUNIOR_SUITE', 'جناح صغير'), ('FAMILY', 'عائلي (Family)'), ('STUDIO', 'استوديو'), ('DELUXE', 'ديلوكس'), ('SUPERIOR', 'سوبيريور'), ('CONNECTING', 'غرفة متصلة'), ('PENTHOUSE', 'بنتهاوس')], default='DOUBLE', max_length=20)),
                ('room_count', models.PositiveSmallIntegerField(default=1)),
                ('beds', models.JSONField(default=list)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('exclude_infants', models.BooleanField(default=False)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('area_unit', models.CharField(choices=[('SQM', 'متر مربع'), ('SQFT', 'قدم مربع')], default='SQM', max_length=6)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('bathroom_private', models.BooleanField(default=True)),
                ('bathroom_items', models.JSONField(default=list)),
                ('room_amenities', models.JSONField(default=list)),
                ('room_name', models.CharField(choices=[('TWIN', 'توأم (Twin)'), ('DOUBLE', 'مزدوج (Double)'), ('SINGLE', 'مفرد (Single)'), ('TRIPLE', 'ثلاثي (Triple)'), ('QUAD', 'رباعي (Quad)'), ('SUITE', 'جناح (Suite)'), ('JUNIOR_SUITE', 'جناح صغير'), ('FAMILY', 'عائلي (Family)'), ('STUDIO', 'استوديو'), ('DELUXE', 'ديلوكس'), ('SUPERIOR', 'سوبيريور'), ('CONNECTING', 'غرفة متصلة'), ('PENTHOUSE', 'بنتهاوس')], default='DOUBLE', max_length=20)),
                ('room_custom_name', models.CharField(blank=True, max_length=100)),
                ('cost_price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_currency', models.CharField(choices=[('MYR', 'Malaysian Ringgit'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('DZD', 'Algerian Dinar')], default='MYR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hotel_room_type',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='suppliers/hotels/images/%Y/%m/')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotel_image',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomOccupancyPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guests_count', models.PositiveSmallIntegerField()),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hotel_room_occupancy_price',
                'ordering': ['-guests_count'],
            },
        ),
        migrations.CreateModel(
            name='SupplierWaitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_type', models.CharField(choices=[('TRANSPORT', 'نقل'), ('RESTAURANT', 'مطاعم'), ('GUIDE', 'مرشد سياحي'), ('ACTIVITY', 'أنشطة'), ('WELLNESS', 'صحة وعافية'), ('HALAL', 'خدمات حلال'), ('ENTERTAINMENT', 'ترفيه'), ('SERVICES', 'خدمات داعمة'), ('OTHER', 'أخرى')], db_index=True, max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=255)),
                ('sub_type', models.CharField(blank=True, help_text='النوع الفرعي: Car Rental, Airport Transfer...', max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('extra_info', models.JSONField(blank=True, default=dict, help_text='معلومات إضافية خاصة بكل نوع')),
                ('is_contacted', models.BooleanField(default=False, help_text='هل تم التواصل معه؟')),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supplier_waitlist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hotelsupplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomtypesupplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='roomratesupplier',
            name='supplier_ro_room_ty_cefdb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='roomratesupplier',
            name='supplier_ro_content_538400_idx',
        ),
        migrations.RemoveIndex(
            model_name='toursupplier',
            name='supplier_to_country_c638bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='toursupplier',
            name='supplier_to_content_f897b3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='roomtypesupplier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hotelsupplier',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotelsupplier',
            name='cancellation_policy',
        ),
        migrations.RemoveField(
            model_name='hotelsupplier',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='hotelsupplier',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='hotelsupplier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotelsupplier',
            name='images',
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='accidental_booking_protection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='address_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='allow_long_stays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='availability_start',
            field=models.CharField(choices=[('ASAP', 'في أقرب وقت ممكن'), ('SPECIFIC_DATE', 'تاريخ محدد')], default='ASAP', max_length=15),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='availability_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='availability_window',
            field=models.PositiveSmallIntegerField(default=365),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='booking_type',
            field=models.CharField(choices=[('INSTANT', 'حجز فوري'), ('REQUEST', 'طلب حجز')], default='INSTANT', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='breakfast_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='breakfast_currency',
            field=models.CharField(choices=[('MYR', 'Malaysian Ringgit'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('DZD', 'Algerian Dinar')], default='MYR', max_length=3),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='breakfast_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='breakfast_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='breakfast_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='business_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='business_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='business_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='business_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='business_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='business_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='calendar_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='calendar_sync_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='cancellation_deadline_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='cancellation_fee_type',
            field=models.CharField(choices=[('FIRST_NIGHT', 'تكلفة الليلة الأولى'), ('FULL_AMOUNT', '100% من السعر')], default='FIRST_NIGHT', max_length=15),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='chain_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='channel_manager_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='checkin_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='checkin_until',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='checkout_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='checkout_until',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='children_age_from',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='children_age_to',
            field=models.PositiveSmallIntegerField(default=17),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='children_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='children_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='children_price_type',
            field=models.CharField(blank=True, default='FREE', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='children_pricing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='contract_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='description_neighborhood',
            field=models.TextField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='description_property',
            field=models.TextField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='has_channel_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='host_bio',
            field=models.TextField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='host_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='hotel_type',
            field=models.CharField(choices=[('HOTEL', 'فندق'), ('GUESTHOUSE', 'بيت ضيافة'), ('BED_BREAKFAST', 'Bed and Breakfast'), ('HOMESTAY', 'Homestay'), ('HOSTEL', 'بيت شباب'), ('CONDO_HOTEL', 'شقة فندقية'), ('CAPSULE_HOTEL', 'فندق كبسول'), ('COUNTRY_HOUSE', 'بيت ريفي'), ('FARM_STAY', 'مزرعة سياحية'), ('INN', 'نزل'), ('MOTEL', 'موتيل'), ('RESORT', 'منتجع'), ('RIAD', 'رياض'), ('LODGE', 'لودج'), ('FLOATING', 'بيت عائم')], default='HOTEL', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='hotels_count',
            field=models.CharField(choices=[('SINGLE', 'فندق واحد'), ('MULTIPLE', 'فنادق متعددة')], default='SINGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='infant_age_from',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='infant_age_to',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='infant_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='infant_price_type',
            field=models.CharField(blank=True, default='FREE', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='invoice_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='invoice_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='invoice_name_type',
            field=models.CharField(choices=[('USER_NAME', 'اسم المستخدم'), ('PROPERTY_NAME', 'اسم العقار'), ('LEGAL_NAME', 'اسم قانوني')], default='PROPERTY_NAME', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='invoice_same_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='is_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='launch_discount_bookings',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='launch_discount_days',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='launch_discount_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='launch_discount_pct',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='license_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='listed_on',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='max_nights',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='open_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='owner_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'فرد'), ('BUSINESS', 'شركة')], default='INDIVIDUAL', max_length=12),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='parking_available',
            field=models.CharField(choices=[('FREE', 'مجاني'), ('PAID', 'مدفوع'), ('NO', 'لا يوجد')], default='NO', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='parking_location',
            field=models.CharField(blank=True, choices=[('ON_SITE', 'في الموقع'), ('OFF_SITE', 'خارج الموقع')], default='ON_SITE', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='parking_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='parking_price_unit',
            field=models.CharField(blank=True, default='DAY', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='parking_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='parking_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='payment_method',
            field=models.CharField(blank=True, default='ONLINE_PLATFORM', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='pets_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='pets_policy',
            field=models.CharField(choices=[('YES', 'مسموح'), ('ON_REQUEST', 'عند الطلب'), ('NO', 'غير مسموح')], default='ON_REQUEST', max_length=15),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='platform_commission_pct',
            field=models.DecimalField(decimal_places=2, default=17, max_digits=5),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='spoken_languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='available_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='baggage_included_kg',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='cabin_class',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First Class')], default='ECONOMY', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='cost_price_adult',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='cost_price_child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='cost_price_infant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='currency',
            field=models.CharField(choices=[('MYR', 'Malaysian Ringgit'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('DZD', 'Algerian Dinar')], default='MYR', max_length=3),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='suppliers.flightroutesupplier'),
        ),
        migrations.AlterField(
            model_name='flightratesupplier',
            name='season_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightroutesupplier',
            name='airline_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='flightroutesupplier',
            name='airline_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightroutesupplier',
            name='destination_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightroutesupplier',
            name='destination_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='flightroutesupplier',
            name='origin_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightroutesupplier',
            name='origin_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='flightroutesupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_routes', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='hotelsupplier',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotelsupplier',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelsupplier',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING_REVIEW', 'بانتظار المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelsupplier',
            name='country',
            field=models.CharField(default='Malaysia', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelsupplier',
            name='hotel_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelsupplier',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsupplier',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsupplier',
            name='star_rating',
            field=models.CharField(choices=[('0', 'غير متوفر'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='hotelsupplier',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_profile', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='available_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING_REVIEW', 'بانتظار المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='cost_price_child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='cost_price_infant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='currency',
            field=models.CharField(choices=[('MYR', 'Malaysian Ringgit'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('DZD', 'Algerian Dinar')], default='MYR', max_length=3),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='date_from',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='date_to',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='meal_plan',
            field=models.CharField(choices=[('RO', 'Room Only'), ('BB', 'Bed & Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Inclusive')], default='RO', max_length=2),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='min_nights',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='suppliers.roomtypesupplier'),
        ),
        migrations.AlterField(
            model_name='roomratesupplier',
            name='season_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtypesupplier',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='roomtypesupplier',
            name='bed_config',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtypesupplier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomtypesupplier',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_room_types', to='suppliers.hotelsupplier'),
        ),
        migrations.AlterField(
            model_name='roomtypesupplier',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='roomtypesupplier',
            name='max_occupancy',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='roomtypesupplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtypesupplier',
            name='total_rooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='suppliers/documents/contracts/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_currency',
            field=models.CharField(choices=[('MYR', 'Malaysian Ringgit'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('DZD', 'Algerian Dinar')], default='MYR', max_length=3),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('PENDING', 'معلق للمراجعة'), ('APPROVED', 'معتمد'), ('SUSPENDED', 'موقوف'), ('REJECTED', 'مرفوض')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('PROPERTY', 'عقارات'), ('TRANSPORT', 'نقل'), ('RESTAURANT', 'مطاعم'), ('GUIDE', 'مرشد سياحي'), ('ACTIVITY', 'أنشطة'), ('WELLNESS', 'صحة وعافية'), ('HALAL', 'خدمات حلال'), ('AIRLINE', 'شركة طيران'), ('TOUR', 'شركة جولات')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='suppliers/documents/trade/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tourratesupplier',
            name='cost_price_child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tourratesupplier',
            name='cost_price_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tourratesupplier',
            name='currency',
            field=models.CharField(choices=[('MYR', 'Malaysian Ringgit'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('DZD', 'Algerian Dinar')], default='MYR', max_length=3),
        ),
        migrations.AlterField(
            model_name='tourratesupplier',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourratesupplier',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourratesupplier',
            name='season_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tourratesupplier',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='suppliers.toursupplier'),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='content_status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING_REVIEW', 'بانتظار المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='duration_days',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='duration_nights',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='exclusions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='inclusions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='itinerary',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='max_pax',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='min_pax',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='transferratesupplier',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transferratesupplier',
            name='currency',
            field=models.CharField(choices=[('MYR', 'Malaysian Ringgit'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('DZD', 'Algerian Dinar')], default='MYR', max_length=3),
        ),
        migrations.AlterField(
            model_name='transferratesupplier',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='suppliers.transferroutesupplier'),
        ),
        migrations.AlterField(
            model_name='transferratesupplier',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('MPV', 'MPV'), ('VAN', 'Van'), ('BUS', 'Bus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transferroutesupplier',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferroutesupplier',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transferroutesupplier',
            name='estimated_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferroutesupplier',
            name='origin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transferroutesupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_routes', to='suppliers.supplier'),
        ),
        migrations.AddIndex(
            model_name='hotelsupplier',
            index=models.Index(fields=['hotel_type', 'star_rating'], name='supplier_ho_hotel_t_08fd4e_idx'),
        ),
        migrations.AddField(
            model_name='hotelpriceplan',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_plans', to='suppliers.hotelsupplier'),
        ),
        migrations.AddField(
            model_name='hotelpropertyamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.hotelamenity'),
        ),
        migrations.AddField(
            model_name='hotelpropertyamenity',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='suppliers.hotelsupplier'),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='suppliers.hotelsupplier'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='suppliers.hotelsupplier'),
        ),
        migrations.AddField(
            model_name='roomoccupancyprice',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_prices', to='suppliers.hotelroomtype'),
        ),
        migrations.AddIndex(
            model_name='supplierwaitlist',
            index=models.Index(fields=['supplier_type', 'is_contacted'], name='supplier_wa_supplie_d8b7ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelpriceplan',
            unique_together={('hotel', 'plan_type')},
        ),
        migrations.AlterUniqueTogether(
            name='hotelpropertyamenity',
            unique_together={('hotel', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='hotelroomtype',
            index=models.Index(fields=['hotel', 'is_active'], name='hotel_room__hotel_i_2628ff_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelroomtype',
            index=models.Index(fields=['content_status'], name='hotel_room__content_22d732_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomoccupancyprice',
            unique_together={('room_type', 'guests_count')},
        ),
    ]
