# Generated by Django 6.0.3 on 2026-04-28 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_amenities_hotel_check_in_time_and_more'),
        ('locations', '0003_alter_country_phone_code'),
        ('suppliers', '0002_hotelamenity_hotelpriceplan_hotelpropertyamenity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsupplier',
            name='city_ref',
            field=models.ForeignKey(blank=True, help_text='ربط بـ City object الفعلي (للبحث في DB)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_suppliers', to='locations.city', verbose_name='المدينة (مرجع)'),
        ),
        migrations.AddField(
            model_name='hotelsupplier',
            name='created_hotel',
            field=models.OneToOneField(blank=True, help_text='الفندق المُنشأ تلقائياً عند الموافقة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_supplier', to='hotels.hotel', verbose_name='الفندق المُنشأ'),
        ),
    ]
