# Generated by Django 6.0.3 on 2026-04-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotelphoto'),
        ('services', '0005_servicephoto'),
        ('suppliers', '0003_hotelsupplier_city_ref_hotelsupplier_created_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_supplier', to='hotels.hotel', verbose_name='الفندق المُنشأ'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_supplier', to='services.service', verbose_name='الخدمة المُنشأة'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='waitlist_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='معرّف طلب Waitlist الأصلي'),
        ),
    ]
