# Generated by Django 6.0.3 on 2026-04-19 13:08

import apps.waitlist_agency.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyWaitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوكالة')),
                ('registration_number', models.CharField(max_length=100, verbose_name='رقم السجل التجاري')),
                ('country', models.CharField(default='Malaysia', max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(verbose_name='العنوان الكامل')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=30, verbose_name='هاتف الوكالة')),
                ('contact_person_name', models.CharField(max_length=150, verbose_name='اسم المسؤول')),
                ('contact_person_position', models.CharField(max_length=100, verbose_name='منصب المسؤول')),
                ('contact_person_phone', models.CharField(max_length=30, verbose_name='هاتف المسؤول')),
                ('trade_license', models.FileField(upload_to=apps.waitlist_agency.models.trade_license_path, verbose_name='الرخصة التجارية')),
                ('owner_id_document', models.FileField(upload_to=apps.waitlist_agency.models.owner_id_path, verbose_name='هوية المالك')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.waitlist_agency.models.logo_path, verbose_name='شعار الوكالة')),
                ('how_did_you_hear', models.CharField(blank=True, choices=[('SOCIAL_MEDIA', 'وسائل التواصل الاجتماعي'), ('REFERRAL', 'توصية من شخص'), ('GOOGLE', 'بحث على Google'), ('EVENT', 'معرض أو فعالية'), ('OTHER', 'أخرى')], max_length=20, verbose_name='كيف سمعت عنا؟')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('CONTACTED', 'تم التواصل'), ('APPROVED', 'موافَق عليه'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('email_sent', models.BooleanField(default=False, verbose_name='أُرسل إيميل التأكيد؟')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قائمة انتظار — وكالة',
                'verbose_name_plural': 'قائمة انتظار — الوكالات',
                'db_table': 'waitlist_agency',
                'ordering': ['-created_at'],
            },
        ),
    ]
