# Generated by Django 6.0.3 on 2026-05-11 12:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_iata', models.CharField(max_length=3)),
                ('destination_iata', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('cabin_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First')], default='economy', max_length=20)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('currency', models.CharField(choices=[('MYR', 'MYR'), ('USD', 'USD'), ('SAR', 'SAR'), ('AED', 'AED'), ('SGD', 'SGD'), ('EUR', 'EUR')], default='MYR', max_length=3)),
                ('display_title', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(choices=[('duffel', 'Duffel')], default='duffel', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_routes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flights_route',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_offer_id', models.CharField(max_length=128)),
                ('owner_iata', models.CharField(blank=True, max_length=3)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_currency', models.CharField(max_length=3)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_duration_min', models.PositiveIntegerField(default=0)),
                ('slices_summary', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='flights.flightroute')),
            ],
            options={
                'db_table': 'flights_offer',
                'ordering': ['total_amount'],
            },
        ),
        migrations.CreateModel(
            name='FlightSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail'), ('CACHE_HIT', 'Cache Hit')], max_length=16)),
                ('offers_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='flights.flightroute')),
            ],
            options={
                'db_table': 'flights_search_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightBookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=32)),
                ('passport_number', models.CharField(blank=True, max_length=64)),
                ('passenger_count', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='flights.flightoffer')),
            ],
            options={
                'db_table': 'flights_booking_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='flights_boo_status_f15866_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='flightroute',
            index=models.Index(fields=['origin_iata', 'destination_iata', 'departure_date'], name='flights_rou_origin__748daf_idx'),
        ),
        migrations.AddIndex(
            model_name='flightroute',
            index=models.Index(fields=['is_active'], name='flights_rou_is_acti_fe2d67_idx'),
        ),
        migrations.AddIndex(
            model_name='flightoffer',
            index=models.Index(fields=['route', 'total_amount'], name='flights_off_route_i_79aa69_idx'),
        ),
        migrations.AddIndex(
            model_name='flightoffer',
            index=models.Index(fields=['provider_offer_id'], name='flights_off_provide_8fd083_idx'),
        ),
        migrations.AddIndex(
            model_name='flightsearchlog',
            index=models.Index(fields=['route', '-created_at'], name='flights_sea_route_i_9cc5c6_idx'),
        ),
    ]
