# Generated by Django 6.0.3 on 2026-05-12 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flightbookingrequest',
            name='flights_boo_status_f15866_idx',
        ),
        migrations.RemoveIndex(
            model_name='flightoffer',
            name='flights_off_route_i_79aa69_idx',
        ),
        migrations.RemoveIndex(
            model_name='flightoffer',
            name='flights_off_provide_8fd083_idx',
        ),
        migrations.RemoveIndex(
            model_name='flightsearchlog',
            name='flights_sea_route_i_9cc5c6_idx',
        ),
        migrations.AlterModelOptions(
            name='flightroute',
            options={'ordering': ['origin_iata', 'destination_iata']},
        ),
        migrations.RemoveIndex(
            model_name='flightroute',
            name='flights_rou_origin__748daf_idx',
        ),
        migrations.AddConstraint(
            model_name='flightroute',
            constraint=models.UniqueConstraint(fields=('origin_iata', 'destination_iata'), name='uniq_flight_route_pair'),
        ),
        migrations.RemoveField(
            model_name='flightoffer',
            name='route',
        ),
        migrations.RemoveField(
            model_name='flightsearchlog',
            name='route',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='cabin_class',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='children',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='last_refreshed_at',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='return_date',
        ),
        migrations.DeleteModel(
            name='FlightBookingRequest',
        ),
        migrations.DeleteModel(
            name='FlightOffer',
        ),
        migrations.DeleteModel(
            name='FlightSearchLog',
        ),
    ]
