# Generated by Django 6.0.3 on 2026-04-27 11:54

import apps.advertising.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_agency_agency_type_agency_city_and_more'),
        ('hotels', '0003_hotel_amenities_hotel_check_in_time_and_more'),
        ('packages', '0004_packageflight_profit_margin_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرّف فريد')),
                ('name', models.CharField(help_text='للأدمن فقط - لا يظهر للزوار', max_length=200, verbose_name='اسم الإعلان (داخلي)')),
                ('ad_type', models.CharField(choices=[('BANNER', 'بنر صورة'), ('HERO_BANNER', 'بنر رئيسي عريض'), ('POPUP', 'نافذة منبثقة'), ('FEATURED_CARD', 'بطاقة مميزة'), ('CAROUSEL_ITEM', 'عنصر سلايدر')], db_index=True, default='BANNER', max_length=20, verbose_name='نوع الإعلان')),
                ('content', models.JSONField(default=dict, help_text='صيغة: {"ar": {"title": "...", "description": "...", "button": "..."}, "en": {...}, "ms": {...}}', verbose_name='المحتوى (متعدد اللغات)')),
                ('image_desktop', models.ImageField(help_text='الحجم الموصى به: 1920x600 للبنرات الكبيرة، 1200x300 للبنرات العادية', upload_to=apps.advertising.models.ad_image_desktop_path, verbose_name='صورة (سطح المكتب)')),
                ('image_mobile', models.ImageField(blank=True, help_text='اختياري — إن تركتها فارغة، تُستخدم صورة سطح المكتب', null=True, upload_to=apps.advertising.models.ad_image_mobile_path, verbose_name='صورة (الهاتف)')),
                ('image_alt_text', models.CharField(blank=True, help_text='مهم لـ SEO وذوي الاحتياجات الخاصة', max_length=255, verbose_name='النص البديل (Alt Text)')),
                ('link_url', models.URLField(blank=True, help_text='URL خارجي — أو اترك فارغاً واستخدم الربط الداخلي', verbose_name='رابط الإعلان')),
                ('link_target', models.CharField(choices=[('SAME_TAB', 'نفس النافذة'), ('NEW_TAB', 'نافذة جديدة')], default='SAME_TAB', max_length=10, verbose_name='فتح الرابط في')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='عطّله لإيقاف العرض دون حذفه', verbose_name='نشط')),
                ('priority', models.PositiveIntegerField(default=50, help_text='0-100 — أعلى = يظهر أولاً', verbose_name='الأولوية')),
                ('weight', models.PositiveIntegerField(default=1, help_text='عند تساوي الأولوية، يُستخدم الوزن للاختيار العشوائي', verbose_name='الوزن (للتدوير)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Phase 2 — اتركها فارغة الآن', max_digits=12, null=True, verbose_name='التكلفة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'db_table': 'ad_creatives',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرّف فريد')),
                ('name', models.CharField(help_text='للاستخدام الداخلي فقط (لا يظهر للزوار)', max_length=200, verbose_name='اسم الحملة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, help_text='اتركه فارغاً للحملات المستمرة', null=True, verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('budget_total', models.DecimalField(blank=True, decimal_places=2, help_text='Phase 2 — اتركها فارغة الآن', max_digits=12, null=True, verbose_name='الميزانية الإجمالية')),
                ('budget_daily', models.DecimalField(blank=True, decimal_places=2, help_text='Phase 2 — اتركها فارغة الآن', max_digits=12, null=True, verbose_name='الميزانية اليومية')),
                ('currency', models.CharField(blank=True, help_text='MYR/USD/EUR', max_length=3, verbose_name='العملة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'حملة إعلانية',
                'verbose_name_plural': 'الحملات الإعلانية',
                'db_table': 'ad_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdTargeting',
            fields=[
                ('creative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='targeting', serialize=False, to='advertising.adcreative', verbose_name='الإعلان')),
                ('languages', models.JSONField(default=list, help_text='JSON list مثل ["ar", "en", "ms"] أو ["all"] للجميع. اتركها [] لإيقاف العرض.', verbose_name='اللغات المستهدفة')),
                ('countries', models.JSONField(default=list, help_text='JSON list مثل ["MY", "SA", "AE"] أو ["all"]', verbose_name='الدول المستهدفة')),
                ('devices', models.JSONField(default=list, help_text='JSON list من: mobile, desktop, tablet', verbose_name='الأجهزة المستهدفة')),
                ('user_types', models.JSONField(default=list, help_text='JSON list: anonymous, tourist, agency, supplier, admin', verbose_name='أنواع المستخدمين')),
                ('max_views_per_user_day', models.PositiveIntegerField(blank=True, help_text='اتركه فارغاً = غير محدود', null=True, verbose_name='حد المشاهدات للمستخدم/اليوم')),
                ('max_views_per_session', models.PositiveIntegerField(blank=True, help_text='اتركه فارغاً = غير محدود', null=True, verbose_name='حد المشاهدات لكل جلسة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'استهداف',
                'verbose_name_plural': 'الاستهدافات',
                'db_table': 'ad_targetings',
            },
        ),
        migrations.AddField(
            model_name='adcreative',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='اختياري — يمكن إنشاء إعلانات مستقلة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatives', to='advertising.adcampaign', verbose_name='الحملة'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_creatives', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='linked_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_creatives', to='accounts.agency', verbose_name='وكالة مرتبطة'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='linked_hotel',
            field=models.ForeignKey(blank=True, help_text='اختياري — لربط الإعلان بفندق محدد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_creatives', to='hotels.hotel', verbose_name='فندق مرتبط'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='linked_package',
            field=models.ForeignKey(blank=True, help_text='اختياري — يربط بـ CustomPackage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_creatives', to='packages.custompackage', verbose_name='باقة مرتبطة'),
        ),
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('placement_key', models.CharField(choices=[('HOME_HERO_TOP', 'الرئيسية - فوق Hero'), ('HOME_HERO_BG', 'الرئيسية - خلفية Hero'), ('HOME_MIDDLE', 'الرئيسية - وسط الصفحة'), ('HOME_BOTTOM', 'الرئيسية - أسفل الصفحة'), ('HOME_SIDEBAR', 'الرئيسية - شريط جانبي'), ('HOME_BANNER_FULL', 'الرئيسية - بنر عريض كامل'), ('SEARCH_TOP', 'صفحة البحث - أعلى النتائج'), ('HOTEL_DETAIL_SIDE', 'صفحة الفندق - جانبي'), ('POPUP_ENTRY', 'نافذة دخول الموقع'), ('POPUP_EXIT', 'نافذة قبل المغادرة'), ('FOOTER_BANNER', 'بنر فوق التذييل'), ('DASHBOARD_TOP', 'لوحة الوكالة - أعلى')], db_index=True, max_length=30, verbose_name='موقع العرض')),
                ('event_type', models.CharField(choices=[('VIEW', 'مشاهدة'), ('CLICK', 'نقرة'), ('CLOSE', 'إغلاق'), ('DISMISS', 'تجاهل')], db_index=True, max_length=10, verbose_name='نوع الحدث')),
                ('session_id', models.CharField(blank=True, help_text='UUID مُولَّد في الـ frontend', max_length=64, verbose_name='معرّف الجلسة')),
                ('ip_hash', models.CharField(blank=True, help_text='SHA256 hash لحماية الخصوصية', max_length=64, verbose_name='IP (مشفّر)')),
                ('language', models.CharField(blank=True, max_length=2, verbose_name='اللغة')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='الدولة')),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'هاتف'), ('desktop', 'سطح مكتب'), ('tablet', 'لوحي')], max_length=10, verbose_name='نوع الجهاز')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='advertising.adcreative', verbose_name='الإعلان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_events', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حدث إعلاني',
                'verbose_name_plural': 'الأحداث الإعلانية',
                'db_table': 'ad_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('placement_key', models.CharField(choices=[('HOME_HERO_TOP', 'الرئيسية - فوق Hero'), ('HOME_HERO_BG', 'الرئيسية - خلفية Hero'), ('HOME_MIDDLE', 'الرئيسية - وسط الصفحة'), ('HOME_BOTTOM', 'الرئيسية - أسفل الصفحة'), ('HOME_SIDEBAR', 'الرئيسية - شريط جانبي'), ('HOME_BANNER_FULL', 'الرئيسية - بنر عريض كامل'), ('SEARCH_TOP', 'صفحة البحث - أعلى النتائج'), ('HOTEL_DETAIL_SIDE', 'صفحة الفندق - جانبي'), ('POPUP_ENTRY', 'نافذة دخول الموقع'), ('POPUP_EXIT', 'نافذة قبل المغادرة'), ('FOOTER_BANNER', 'بنر فوق التذييل'), ('DASHBOARD_TOP', 'لوحة الوكالة - أعلى')], db_index=True, max_length=30, verbose_name='موقع العرض')),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, help_text='اتركه فارغاً للعرض المستمر', null=True, verbose_name='تاريخ الانتهاء')),
                ('active_hours_start', models.TimeField(blank=True, help_text='مثال: 09:00 — اتركها فارغة للعرض على مدار 24 ساعة', null=True, verbose_name='ساعة البدء (يومياً)')),
                ('active_hours_end', models.TimeField(blank=True, help_text='مثال: 23:00', null=True, verbose_name='ساعة الانتهاء (يومياً)')),
                ('active_weekdays', models.JSONField(blank=True, default=list, help_text='JSON list of integers 0-6 (0=الإثنين, 6=الأحد). اتركها فارغة [] للعرض كل الأيام.', verbose_name='أيام الأسبوع النشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='advertising.adcreative', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'موقع عرض',
                'verbose_name_plural': 'مواقع العرض',
                'db_table': 'ad_placements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['is_active', 'ad_type'], name='ad_creative_is_acti_ef60b3_idx'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['-priority'], name='ad_creative_priorit_9eccaa_idx'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['creative', 'event_type', '-created_at'], name='ad_events_creativ_0944ac_idx'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['placement_key', '-created_at'], name='ad_events_placeme_fa6e61_idx'),
        ),
        migrations.AddIndex(
            model_name='adplacement',
            index=models.Index(fields=['placement_key', 'start_date'], name='ad_placemen_placeme_819daf_idx'),
        ),
    ]
