# Generated by Django 6.0.3 on 2026-04-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreative',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='يُستخدم فقط لـ HOME_HERO_CAROUSEL — صورة كبيرة (1920×1080)', null=True, upload_to='advertising/hero_backgrounds/', verbose_name='صورة خلفية Hero (اختياري)'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='hero_location',
            field=models.CharField(blank=True, help_text='يُستخدم فقط لـ HOME_HERO_CAROUSEL — مثل: Kuala Lumpur', max_length=100, verbose_name='الموقع المعروض (اختياري)'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='hero_logo',
            field=models.ImageField(blank=True, help_text='يُستخدم فقط لـ HOME_HERO_CAROUSEL — شعار الفندق (PNG شفاف)', null=True, upload_to='advertising/hero_logos/', verbose_name='شعار Hero (اختياري)'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='hero_stars',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 — يُستخدم فقط لـ HOME_HERO_CAROUSEL', null=True, verbose_name='عدد النجوم (اختياري)'),
        ),
        migrations.AlterField(
            model_name='adevent',
            name='placement_key',
            field=models.CharField(choices=[('HOME_HERO_CAROUSEL', 'الرئيسية - بطاقات Hero الدوّارة'), ('HOME_HERO_TOP', 'الرئيسية - فوق Hero'), ('HOME_HERO_BG', 'الرئيسية - خلفية Hero'), ('HOME_MIDDLE', 'الرئيسية - وسط الصفحة'), ('HOME_BOTTOM', 'الرئيسية - أسفل الصفحة'), ('HOME_SIDEBAR', 'الرئيسية - شريط جانبي'), ('HOME_BANNER_FULL', 'الرئيسية - بنر عريض كامل'), ('SEARCH_TOP', 'صفحة البحث - أعلى النتائج'), ('HOTEL_DETAIL_SIDE', 'صفحة الفندق - جانبي'), ('POPUP_ENTRY', 'نافذة دخول الموقع'), ('POPUP_EXIT', 'نافذة قبل المغادرة'), ('FOOTER_BANNER', 'بنر فوق التذييل'), ('DASHBOARD_TOP', 'لوحة الوكالة - أعلى')], db_index=True, max_length=30, verbose_name='موقع العرض'),
        ),
        migrations.AlterField(
            model_name='adplacement',
            name='placement_key',
            field=models.CharField(choices=[('HOME_HERO_CAROUSEL', 'الرئيسية - بطاقات Hero الدوّارة'), ('HOME_HERO_TOP', 'الرئيسية - فوق Hero'), ('HOME_HERO_BG', 'الرئيسية - خلفية Hero'), ('HOME_MIDDLE', 'الرئيسية - وسط الصفحة'), ('HOME_BOTTOM', 'الرئيسية - أسفل الصفحة'), ('HOME_SIDEBAR', 'الرئيسية - شريط جانبي'), ('HOME_BANNER_FULL', 'الرئيسية - بنر عريض كامل'), ('SEARCH_TOP', 'صفحة البحث - أعلى النتائج'), ('HOTEL_DETAIL_SIDE', 'صفحة الفندق - جانبي'), ('POPUP_ENTRY', 'نافذة دخول الموقع'), ('POPUP_EXIT', 'نافذة قبل المغادرة'), ('FOOTER_BANNER', 'بنر فوق التذييل'), ('DASHBOARD_TOP', 'لوحة الوكالة - أعلى')], db_index=True, max_length=30, verbose_name='موقع العرض'),
        ),
    ]
