# Generated by Django 6.0.3 on 2026-05-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_adcreative_hero_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreative',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='للربط بأنظمة قديمة (مثل hero_hotel_card_id)', verbose_name='بيانات إضافية'),
        ),
    ]
