# Generated by Django 6.0.3 on 2026-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_adcreative_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcreative',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='adcreative',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='adcreative',
            name='hero_location',
        ),
        migrations.RemoveField(
            model_name='adcreative',
            name='hero_logo',
        ),
        migrations.RemoveField(
            model_name='adcreative',
            name='hero_stars',
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='ad_type',
            field=models.CharField(choices=[('BANNER', 'بنر صورة'), ('HERO_BANNER', 'بنر رئيسي عريض'), ('POPUP', 'نافذة منبثقة'), ('FEATURED_CARD', 'بطاقة مميزة')], db_index=True, default='BANNER', max_length=20, verbose_name='نوع الإعلان'),
        ),
        migrations.AlterField(
            model_name='adevent',
            name='placement_key',
            field=models.CharField(choices=[('HOME_HERO_TOP', 'الرئيسية - فوق Hero'), ('HOME_HERO_BG', 'الرئيسية - خلفية Hero'), ('HOME_MIDDLE', 'الرئيسية - وسط الصفحة'), ('HOME_BOTTOM', 'الرئيسية - أسفل الصفحة'), ('HOME_SIDEBAR', 'الرئيسية - شريط جانبي'), ('HOME_BANNER_FULL', 'الرئيسية - بنر عريض كامل'), ('SEARCH_TOP', 'صفحة البحث - أعلى النتائج'), ('HOTEL_DETAIL_SIDE', 'صفحة الفندق - جانبي'), ('POPUP_ENTRY', 'نافذة دخول الموقع'), ('POPUP_EXIT', 'نافذة قبل المغادرة'), ('FOOTER_BANNER', 'بنر فوق التذييل'), ('DASHBOARD_TOP', 'لوحة الوكالة - أعلى')], db_index=True, max_length=30, verbose_name='موقع العرض'),
        ),
        migrations.AlterField(
            model_name='adplacement',
            name='placement_key',
            field=models.CharField(choices=[('HOME_HERO_TOP', 'الرئيسية - فوق Hero'), ('HOME_HERO_BG', 'الرئيسية - خلفية Hero'), ('HOME_MIDDLE', 'الرئيسية - وسط الصفحة'), ('HOME_BOTTOM', 'الرئيسية - أسفل الصفحة'), ('HOME_SIDEBAR', 'الرئيسية - شريط جانبي'), ('HOME_BANNER_FULL', 'الرئيسية - بنر عريض كامل'), ('SEARCH_TOP', 'صفحة البحث - أعلى النتائج'), ('HOTEL_DETAIL_SIDE', 'صفحة الفندق - جانبي'), ('POPUP_ENTRY', 'نافذة دخول الموقع'), ('POPUP_EXIT', 'نافذة قبل المغادرة'), ('FOOTER_BANNER', 'بنر فوق التذييل'), ('DASHBOARD_TOP', 'لوحة الوكالة - أعلى')], db_index=True, max_length=30, verbose_name='موقع العرض'),
        ),
    ]
