# Generated by Django 6.0.3 on 2026-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingflight_bookinggift_bookingroom_bookingtour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghotel',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('triple', 'Triple'), ('family', 'Family'), ('suite', 'Suite'), ('deluxe', 'Deluxe')], default='double', max_length=20, verbose_name='نوع الغرفة'),
        ),
    ]
