# Generated by Django 6.0.3 on 2026-05-04 02:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('hotels', '0005_hotelphoto'),
        ('services', '0006_service_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('ms', 'Malay')], default='ar', max_length=2)),
                ('verified', models.BooleanField(default=False, help_text='True when linked to an actual completed booking')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='bookings.booking')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'is_published', '-created_at'], name='reviews_rev_hotel_i_1efbd0_idx'), models.Index(fields=['service', 'is_published', '-created_at'], name='reviews_rev_service_f65a99_idx'), models.Index(fields=['user', '-created_at'], name='reviews_rev_user_id_eeecea_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('hotel__isnull', False), ('service__isnull', True)), models.Q(('hotel__isnull', True), ('service__isnull', False)), _connector='OR'), name='review_targets_exactly_one_entity')],
            },
        ),
    ]
