# Generated by Django 6.0.3 on 2026-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='breakfast_included',
            field=models.BooleanField(default=False, verbose_name='يشمل الإفطار'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='currency',
            field=models.CharField(default='MYR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الخصم (%)'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='السعر لليلة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='season_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الموسم'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='سارية من'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='سارية إلى'),
        ),
    ]
