# Generated by Django 6.0.3 on 2026-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomtype_breakfast_included_roomtype_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='breakfast_included',
            field=models.BooleanField(default=False, verbose_name='يشمل فطور الصباح'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='currency',
            field=models.CharField(blank=True, default='MYR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر لليلة'),
        ),
    ]
