# Generated by Django 6.0.3 on 2026-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_booking', 'حجز جديد'), ('booking_status', 'تغيير حالة حجز'), ('new_agency', 'وكالة جديدة'), ('agency_approved', 'قبول وكالة'), ('agency_rejected', 'رفض وكالة'), ('new_supplier', 'مورّد جديد'), ('supplier_approved', 'قبول مورّد'), ('supplier_rejected', 'رفض مورّد')], max_length=20, verbose_name='نوع الإشعار'),
        ),
    ]
